apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-backend
  namespace: journal-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-backend
  template:
    metadata:
      labels:
        app: journal-backend
    spec:
      containers:
        - name: journal-backend
          image: diggikadiyam/journal-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/research_journal_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2220"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: journal-backend-service
  namespace: journal-system
spec:
  selector:
    app: journal-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
