apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-frontend
  namespace: journal-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-frontend
  template:
    metadata:
      labels:
        app: journal-frontend
    spec:
      containers:
        - name: journal-frontend
          image: diggikadiyam/journal-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: journal-frontend-service
  namespace: journal-system
spec:
  type: ClusterIP
  selector:
    app: journal-frontend
  ports:
    - port: 80
      targetPort: 80
