name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: diggikadiyam
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------
      # Build & Push BACKEND
      # -------------------------
      - name: Build backend image
        run: |
          docker build -t diggikadiyam/journal-backend:latest \
          "research-journal-backends"

      - name: Push backend image
        run: |
          docker push diggikadiyam/journal-backend:latest

      # -------------------------
      # Build & Push FRONTEND
      # -------------------------
      - name: Build frontend image
        run: |
          docker build -t diggikadiyam/journal-frontend:latest \
          "Research Journal Management System"

      - name: Push frontend image
        run: |
          docker push diggikadiyam/journal-frontend:latest
